### ISSUE TITLE
har-validator in package.json is incorrect version

### ISSUE THREAD

**Issue by Grant-Steinfeld** [horeaporutiu/VSCodeLocalNetwork#3]
when running npm-install I get the error:

npm ERR! code E404
npm ERR! 404 Not Found: har-validator@5.1.2

changing package-lock.json
line 1609  from 
"version": "5.1.2"
to
"version": "5.1.3"

and

line 1611
   "resolved": "https://registry.npmjs.org/har-validator/-/har-validator-5.1.2.tgz",
to
    "resolved": "https://registry.npmjs.org/har-validator/-/har-validator-5.1.3.tgz",

and removing 
line 1611 "integrity" (i.e. the sha )

then re running npm install fixes it

ref: https://github.com/ahmadnassri/node-har-validator/issues/113

thanks!!

Grant

**Comment by horeaporutiu** [comment]
Thanks, just merged a PR that hopefully fixes this..could you try again and see if it works now?

**Comment by Grant-Steinfeld** [comment]
OK cool - been trying your new repo -- I'll slack you :)
